server.port: 8091
spring.application.name: config-client
#spring.cloud.config.enabled: false

spring.config.import: optional:configserver:http://localhost:8888
management.security.enabled: false
management.endpoints.web.exposure.include: '*'

spring.profiles.active: prod

---
spring:
  profiles: dev

message: dev message
